app/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'ticket#index'
  get 'priorities', to: 'ticket#priorities', as: :priorities

  get 'create/board', to: 'ticket#board_create', as: :create_board_page
  get 'create/ticket', to: 'ticket#ticket_create', as: :create_ticket_page
  post 'create/board', to: 'ticket#board_create_back', as: :create_board
  post 'create/ticket', to: 'ticket#ticket_create_back', as: :create_ticket

  get 'share/ticket/:id', to: 'ticket#share_ticket_page', as: :share_ticket_page
  post 'share/ticket/:id', to: 'ticket#share_ticket', as: :share_ticket

  get 'login', to: 'user#login', as: :login
  get 'register', to: 'user#register', as: :register
  get 'logout', to: 'user#logout', as: :logout

  post 'login', to: 'user#login_back', as: :login_back
  post 'register', to: 'user#register_back', as: :register_back

  get 'delete/ticket/:id', to: 'ticket#delete_ticket', as: :delete_ticket
  get 'delete/board/:id', to: 'ticket#delete_board', as: :delete_board

end

app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  has_many :tickets
end

app/app/models/priority.rb
class Priority < ApplicationRecord
  def self.get_title(id)
    Priority.find_by(id: id).title
  end
end

app/app/models/share.rb
class Share < ApplicationRecord
  belongs_to :ticket
  belongs_to :user

  def self.get_by_ticket(id)
    Share.where(ticket_id: id)
  end

  def self.get_by_user(id)
    Ticket.where(id: Share.where(user_id: id).select(:ticket_id))
  end
end

app/app/models/tag.rb
class Tag < ApplicationRecord
end

app/app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  belongs_to :priority
  belongs_to :board
  has_many :shares

end

app/app/models/user.rb
class User < ApplicationRecord
  has_many :tickets
  has_many :boards
  has_many :shares
end

app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def auth
    session[:auth]
  end
end

app/app/controllers/ticket_controller.rb
class TicketController < ApplicationController
  def index
    if auth
      @boards = Board.where(user_id: auth['id'])
    else
      redirect_to login_path
    end
  end

  def priorities
    if auth
      @priorities = Priority.all
      @tickets = Ticket.where(user_id: auth['id'])
      render 'priorities'
    else
      redirect_to login_path
    end
  end

  def board_create_back
    @board = Board.new
    @board.title = params[:title]
    @board.user_id = auth['id']
    @board.save
    redirect_to root_path
  end

  def ticket_create
    @priorities = Priority.all
    @boards = Board.where(user_id: auth['id'])
  end

  def ticket_create_back
    @ticket = Ticket.new
    @ticket.title = params[:title]
    @ticket.content = params[:content]
    @ticket.user_id = auth['id']
    @ticket.priority_id = params[:priority_id]
    @ticket.board_id = params[:board_id]
    @ticket.assignee_date = params[:assignee_date]
    @ticket.tags = params[:tags]
    @ticket.save
    redirect_to root_path
  end

  def delete_ticket
    if @ticket = Ticket.find_by(id: params[:id]) and @ticket.user_id == auth['id']
      @ticket.destroy
      redirect_to root_path, notice: "Успешно удалено!"
    else
      redirect_to root_path, notice: "У вас нет на это прав"
    end
  end

  def delete_board
    if @ticket = Board.find_by(id: params[:id]) and @ticket.user_id == auth['id']
      @ticket.destroy
      redirect_to root_path, notice: "Успешно удалено!"
    else
      redirect_to root_path, notice: "У вас нет на это прав"
    end
  end

  def share_ticket_page
    render 'share'
  end

  def share_ticket
    if Share.find_by(ticket_id: params[:ticket_id], user_id: params[:user_id])
      redirect_to root_path, notice: "Вы уже делитесь с этим пользователем"
    else
      @share = Share.new
      @share.user_id = params[:user_id]
      @share.ticket_id = params[:ticket_id]
      @share.save
      redirect_to root_path, notice: "Теперь этот пользователь видит вашу задачу!"
    end
  end

end

app/app/controllers/user_controller.rb
class UserController < ApplicationController
  def login_back
    if @user = User.find_by(email: params[:email], password: params[:password])
      session[:auth] = @user
      redirect_to root_path
    else
      redirect_to login_path, notice: "Неверная почта или пароль"
    end
  end

  def register_back
    if User.find_by(email: params[:email]).nil?
      @user = User.new
      @user.email = params[:email]
      @user.password = params[:password]
      @user.name = params[:name]
      @user.last_name = params[:last_name]
      if @user.save
        session[:auth] = @user
        redirect_to root_path
      else
        redirect_to register_path, notice: "Ошибка сервера. Попробуйте позже"
      end
    else
      redirect_to register_path, notice: "Пользователь с такой почтой уже зарегистрирован"
    end
  end

  def logout
    session[:auth] = nil
    redirect_to root_path
  end
end

app/app/helpers/application_helper.rb
module ApplicationHelper
  def auth
    session[:auth]
  end

  def format_date(date)
    d = date.in_time_zone("Almaty")
    d.strftime("%d.%m.%Y") == DateTime.now.in_time_zone("Almaty").strftime("%d.%m.%Y") ? "Сегодня в #{d.strftime("%H:%M")}" : d.strftime("%d.%m.%Y %H:%M")
  end
end

app/app/helpers/ticket_helper.rb
module TicketHelper
end

app/app/helpers/user_helper.rb
module UserHelper
end

app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Checkitout</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <header class="header">
      <div class="container">
        <h1 class="logo">
          <a href="<%= root_path %>">
            Checkitout
          </a>
        </h1>
        <nav class="navigation">
          <% unless auth %>
            <a href="<%= register_path %>" class="navigation__item">Зарегистрироваться</a>
            <a href="<%= login_path %>" class="navigation__item">Войти</a>
          <% else %>
            <a href="<%= create_board_page_path %>" class="navigation__item">Создать доску</a>
            <a href="<%= create_ticket_page_path %>" class="navigation__item">Создать задачу</a>
            <a href="<%= root_path %>" class="navigation__item">Мое расписание</a>
            <a href="<%= logout_path %>" class="navigation__item">Выйти</a>
          <% end %>
        </nav>
      </div>
    </header>
    <% if notice %>
      <div class="notice">
        <div class="container">
          <%= notice %>
        </div>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/app/views/ticket/board_create.html.slim
main.tickets
  .container
    h1.title = "Создать доску"
    = form_with url: create_board_path, method: :post do |f|
      = f.text_field :title, placeholder: "Название доски", class: "form__field"
      = f.submit "Создать", class: "form__button"

app/app/views/ticket/index.html.slim
main.tickets
  .container
    .flex
      h1.title = "Ваша доска задач"
      a href=priorities_path = "По приоритету"
    .grid
      - @boards.each do |p|
        .grid__item.board
          h2.subtitle
            = p.title
            a.delete-board.red href=delete_board_path(p.id) = "Удалить доску"
          - p.tickets.order(assignee_date: :asc).each do |t|
            .ticket
              span.ticket__title = t.title
              p.ticket__content = t.content
              .flex style="margin-bottom: 10px"
                span = "Приоритет:"
                span = t.priority.title
              .flex style="margin-bottom: 10px"
                span = "Время:"
                = form_with do |form|
                  = form.text_field :assignee_date, value: format_date(t.assignee_date), disabled: true
              - if t.tags
                .tags
                  - t.tags.split(',').each do |tag|
                    .tag = tag
              - if Share.get_by_ticket(t.id).length != 0
                .tags
                  span style="display: block; margin-top: 20px; color: grey; margin-bottom: 5px" = "Делитесь с:"
                  - Share.get_by_ticket(t.id).each do |tag|
                    .tag = tag.user.name
              a.delete href=delete_ticket_path(t.id) = "Удалить задачу"
              a.delete href=share_ticket_path(t.id) = "Поделиться задачей"
          - if p.tickets.length == 0
            .empty = "Пусто"

      .grid__item.board.shared
        h2.subtitle = "Задачи которыми с вами поделились"
        - Share.get_by_user(auth['id']).order(assignee_date: :asc).each do |t|
          .ticket
            span.ticket__title = t.title
            p.ticket__content = t.content
            .flex style="margin-bottom: 10px"
              span = "Приоритет:"
              span = t.priority.title
            .flex style="margin-bottom: 10px"
              span = "Время:"
              = form_with do |form|
                = form.text_field :assignee_date, value: format_date(t.assignee_date), disabled: true
            - if t.tags
              .tags
                - t.tags.split(',').each do |tag|
                  .tag = tag
            - if Share.get_by_ticket(t.id).length != 0
              .tags
                span style="display: block; margin-top: 20px; color: grey; margin-bottom: 5px" = "Делитесь с:"
                - Share.get_by_ticket(t.id).each do |tag|
                  .tag = tag.user.name
        - if Share.get_by_user(auth['id']).length == 0
          .empty = "С вами еще никто не поделился задачей"

app/app/views/ticket/priorities.slim
main.tickets
  .container
    h1.title = "Ваши задачи по приоритету"
    .grid
      - @priorities.each do |p|
        .grid__item
          h2.subtitle
            = p.title
          - @tickets.where(priority_id: p).order(assignee_date: :asc).each do |t|
            .ticket
              span.ticket__title = t.title
              p.ticket__content = t.content
              .flex style="margin-bottom: 10px"
                span = "Время:"
                = form_with do |form|
                  = form.text_field :assignee_date, value: format_date(t.assignee_date), disabled: true
              - if t.tags
                .tags
                  - t.tags.split(',').each do |tag|
                    .tag = tag
              a.delete href=delete_ticket_path(t.id) = "Удалить задачу"
          - if @tickets.where(priority_id: p).length == 0
            .empty = "Пусто"

app/app/views/ticket/share.html.slim
main.tickets
  .container
    h1.title = "Поделиться"
    = form_with url: share_ticket_path, method: :post do |f|
      .flex style="margin-bottom: 10px;"
        span = "Выберите пользователя с которым хотите поделиться задачей"
        select name="user_id"
          - User.all.each do |b|
            option value=b.id = b.name + " " + b.last_name
        input type="text" name="ticket_id" hidden="true" value=params[:id]
      = f.submit "Создать", class: "form__button"

app/app/views/ticket/ticket_create.html.slim
main.tickets
  .container style="max-width: 500px"
    h1.title = "Создать задачу"
    = form_with url: create_ticket_path, method: :post do |f|
      = f.text_field :title, placeholder: "Заголовок задачи", class: "form__field"
      = f.text_area :content, placeholder: "Описание задачи", class: "form__field"
      .flex style="margin-bottom: 10px;"
        span = "Приоритет"
        select name="priority_id"
          - @priorities.each do |p|
            option value=p.id = p.title
      .flex style="margin-bottom: 10px;"
        span = "Доска"
        select name="board_id"
          - @boards.each do |b|
            option value=b.id = b.title
      .flex style="margin-bottom: 10px;"
        span = "Дата назначения"
        = f.datetime_field :assignee_date
      = f.text_area :tags, placeholder: "Теги (через запятую, без пробелов. Прим: тег1,тег2,тег3)", class: "form__field"
      = f.submit "Создать", class: "form__button"

app/app/views/user/login.html.slim
main.login
  .container
    h2.title = "Войти"
    = form_with url: login_back_path, method: :post do |f|
      = f.text_field :email, placeholder: "Электронная почта", class: "form__field"
      = f.password_field :password, placeholder: "Пароль", class: "form__field"
      = f.submit "Войти", class: "form__button"
      a.form__link  href=register_path = "Нет аккаунта?"

app/app/views/user/register.html.slim
main.login
  .container
    h2.title = "Зарегистрироваться"
    = form_with url: register_back_path, method: :post do |f|
      = f.text_field :name, placeholder: "Ваше имя", class: "form__field"
      = f.text_field :last_name, placeholder: "Ваша фамилия", class: "form__field"
      = f.text_field :email, placeholder: "Электронная почта", class: "form__field"
      = f.password_field :password, placeholder: "Пароль", class: "form__field"
      = f.submit "Зарегистрироваться", class: "form__button"
      a.form__link  href=login_path = "Уже зарегистрированы?"